[ubuntu]
ubuntu_veeb1 ansible_host=172.17.30.12 ansible_user=administrator
ubuntu_veeb2 ansible_host=172.17.30.8 ansible_user=administrator
ubuntu_reverse_proxy ansible_host=172.17.30.9 ansible_user=administrator
ubuntu_klient1 ansible_host=172.17.10.4 ansible_user=naised
ubuntu_klient2 ansible_host=172.17.10.5 ansible_user=naised

[centos]
centos_monitor ansible_host=172.17.30.6 ansible_user=root
centos_siem ansible_host=172.17.30.7 ansible_user=root

[linux:children]
ubuntu
centos

[all:vars]
ansible_python_interpreter=/usr/bin/python3
